FROM docker.elastic.co/elasticsearch/elasticsearch:8.13.4

# nori 플러그인 설치
RUN elasticsearch-plugin install analysis-nori

# --- root 권한으로 전환 ---
USER root

# 필요하다면 logs 디렉토리를 미리 만들어놓거나 다른 설정 가능
# (단, 마운트될 경로는 호스트에서 연결되므로, 컨테이너 내부에 디렉토리를 만들 필요는 보통 없음)

# --- 다시 elasticsearch 유저로 전환 ---
USER elasticsearch

# 사용자 사전, synonyms COPY
RUN mkdir -p /usr/share/elasticsearch/config/analysis
COPY userdict_ko.txt /usr/share/elasticsearch/config/analysis/userdict_ko.txt
COPY synonyms.txt    /usr/share/elasticsearch/config/analysis/synonyms.txt

# 단일노드 모드, 보안 비활성
ENV discovery.type=single-node
ENV xpack.security.enabled=false

# 파일 인코딩 옵션
ENV ES_JAVA_OPTS "-Dfile.encoding=UTF-8 -Dclient.encoding.override=UTF-8"
